services:
  - type: web
    name: muslim-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: 8298951678:AAGHWFexDQXoNCLyWOcR7_DL1XkZFRA_B-E
        sync: false
      - key: PORT
        value: 10000